default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_twygo_lms_development

test:
  <<: *default
  database: test_twygo_lms_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", '') %>
